GH-33787: [C++] Suppress unused-value warning from LinuxParseCpuFlags() on s390x (#33828)
### Rationale for this change

Building at the s390x with the -Werror triggers an error:

    arrow/cpp/src/arrow/util/cpu_info.cc:155:3: error: statement has no effect [-Werror=unused-value].

### What changes are included in this PR?

Just returns `0` in `LinuxParseCpuFlags()` on non-(x86_64|arm64) environment.

### Are these changes tested?

Local test.

### Are there any user-facing changes?

No.

Closes https://github.com/apache/arrow/issues/33787.

Signed-off-by: Aliaksei Makarau <aliaksei.makarau@ ibm.com>

Authored-by: Aliaksei Makarau <aliaksei.makarau@ibm.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>