ARROW-4676: [C++] Add support for debug build with MinGW
We need to suppress all warnings for debug build.

Messages:

    cpp/src/arrow/util/cpu-info.cc: In function 'bool arrow::internal::RetrieveCacheSize(int64_t*)':
    cpp/src/arrow/util/cpu-info.cc:127:12: error: conversion from 'long long unsigned int' to 'DWORD' {aka 'long unsigned int'} may change value [-Werror=conversion]
         offset += sizeof(SYSTEM_LOGICAL_PROCESSOR_INFORMATION);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cpp/src/arrow/util/cpu-info.cc: In function 'bool arrow::internal::RetrieveCPUInfo(int64_t*, std::__cxx11::string*)':
    cpp/src/arrow/util/cpu-info.cc:159:33: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
       if (highest_extended_valid_id >= 0x80000004) {
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
    cpp/src/arrow/util/cpu-info.cc:161:32: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
         for (int i = 0x80000002; i <= 0x80000004; ++i) {
                                  ~~^~~~~~~~~~~~~
    cpp/src/arrow/util/cpu-info.cc: At global scope:
    cpp/src/arrow/util/cpu-info.cc:77:9: warning: 'int64_t arrow::internal::{anonymous}::ParseCPUFlags(const string&)' defined but not used [-Wunused-function]
     int64_t ParseCPUFlags(const std::string& values) {
             ^~~~~~~~~~~~~

    cpp/src/arrow/util/io-util.cc: In function 'arrow::Status arrow::internal::FileRead(int, uint8_t*, int64_t, int64_t*)':
    cpp/src/arrow/util/io-util.cc:408:57: error: conversion from 'size_t' {aka 'long long unsigned int'} to 'unsigned int' may change value [-Werror=conversion]
         int64_t ret = static_cast<int64_t>(read(fd, buffer, static_cast<size_t>(chunksize)));
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cpp/src/arrow/util/io-util.cc: In function 'arrow::Status arrow::internal::FileWrite(int, const uint8_t*, int64_t)':
    cpp/src/arrow/util/io-util.cc:476:43: [ error: 75conversion from '%  size_tBuilding CXX object src/arrow/CMakeFiles/arrow_objlib.dir/util/memory.cc.obj' {aka '
    long long unsigned int'} to 'unsigned int' may change value [-Werror=conversion]
             write(fd, buffer + bytes_written, static_cast<size_t>(chunksize)));
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Author: Kouhei Sutou <kou@clear-code.com>

Closes #3750 from kou/cpp-add-support-debug-build-with-mingw and squashes the following commits:

4dc7fc74 <Kouhei Sutou>  Add support for debug build with MinGW