ARROW-11724: [C++] Resolve namespace collisions with protobuf 3.15
Renames our alias to `afpb` to not clash with `protobuf`'s definition.

Original error:

```
../src/arrow/flight/server.cc:63:11: error: redefinition of 'pb' as an alias for a different namespace
namespace pb = arrow::flight::protocol;
          ^
/Users/uwe/mambaforge/conda-bld/arrow-cpp-ext_1613940663852/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/google/protobuf/port.h:44:11: note: previously defined as an alias for 'protobuf_future_namespace_placeholder'
namespace pb = ::protobuf_future_namespace_placeholder;
          ^
1 error generated.
```

Closes #9542 from xhochy/ARROW-11724

Authored-by: Uwe L. Korn <uwe.korn@quantco.com>
Signed-off-by: Antoine Pitrou <antoine@python.org>