ARROW-6884: [Python] Format friendlier message in Python when a server-side RPC handler fails
I added a "Failure" Flight error code to communicate to Python to create the ServerError exception type.

Now we have server exceptions like

```
pyarrow._flight.FlightServerError: Flight RPC failed with Python exception "TypeError: Results of list_actions must be ActionType or tuple"
```

instead of

```
pyarrow.lib.ArrowException: Unknown error: gRPC returned unknown error, with message: Results of list_actions must be ActionType or tuple. Detail: Python exception: TypeError
```

It's a small thing but makes it more clear what's going on.

Closes #5662 from wesm/ARROW-6884 and squashes the following commits:

7d7bc0c65 <Wes McKinney> Compile regex, also work with ARROW_EXTRA_ERROR_CONTEXT=ON
bc29d93b7 <Wes McKinney> Munge the error message to be more beautiful
55e05d533 <Wes McKinney> Format friendlier message in Python when a server-side RPC handler fails

Authored-by: Wes McKinney <wesm+git@apache.org>
Signed-off-by: Wes McKinney <wesm+git@apache.org>