ARROW-18186: [C++][MinGW] Make buildable with clang (#14536)
Error1 (can't use `[[gnu::dllexport]]` with template):

    cpp/src/arrow/util/int_util.cc:463:1: error: an attribute list cannot appear here
    INSTANTIATE_ALL()
    ^~~~~~~~~~~~~~~~~
    cpp/src/arrow/util/int_util.cc:454:3: note: expanded from macro 'INSTANTIATE_ALL'
      INSTANTIATE_ALL_DEST(uint8_t)  \
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cpp/src/arrow/util/int_util.cc:444:3: note: expanded from macro 'INSTANTIATE_ALL_DEST'
      INSTANTIATE(uint8_t, DEST)       \
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
    cpp/src/arrow/util/int_util.cc:440:12: note: expanded from macro 'INSTANTIATE'
      template ARROW_TEMPLATE_EXPORT void TransposeInts( \
               ^~~~~~~~~~~~~~~~~~~~~
    cpp/src/arrow/util/visibility.h:47:31: note: expanded from macro 'ARROW_TEMPLATE_EXPORT'
    #define ARROW_TEMPLATE_EXPORT ARROW_DLLEXPORT
                                  ^~~~~~~~~~~~~~~
    cpp/src/arrow/util/visibility.h:32:25: note: expanded from macro 'ARROW_DLLEXPORT'
    #define ARROW_DLLEXPORT [[gnu::dllexport]]
                            ^~~~~~~~~~~~~~~~~~

Error2 (unused variable):

    cpp/src/arrow/util/io_util.cc:1079:7: warning: variable 'oflag' set but not used [-Wunused-but-set-variable]
      int oflag = _O_CREAT | _O_BINARY | _O_NOINHERIT;
          ^

Error3 (missing field initializers):

    cpp/src/arrow/util/io_util.cc:1545:29: warning: missing field 'InternalHigh' initializer [-Wmissing-field-initializers]
      OVERLAPPED overlapped = {0};
                                ^

Authored-by: Sutou Kouhei <kou@clear-code.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>