ARROW-18366: [Packaging][RPM][Gandiva] Fix link error on AlmaLinux 9 (#14680)
LLVM is built with gcc-toolset-12 and it can't be used with the default g++. We also need to use gcc-toolset-12.

Error message:

    /usr/bin/ld: .../libgandiva.so.1100: undefined reference to
    `std::__glibcxx_assert_fail(char const*, int, char const*, char const*)'

Authored-by: Sutou Kouhei <kou@clear-code.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>