ARROW-4395: [JS] Fix ts-node error running bin/arrow2csv
`ts-node` type-checking is inaccurate, because it only checks files that are touched by node's `require()` calls, leading to errors like this:
```sh
$ cat test/data/cpp/stream/simple.arrow | ./bin/arrow2csv.js

/home/ptaylor/dev/arrow/js/node_modules/ts-node/src/index.ts:228
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/vector/map.ts(25,57): error TS2345: Argument of type 'Field<T[string | number | symbol]>[]' is not assignable to parameter of type 'Field<T[keyof T]>[]'.
  Type 'Field<T[string | number | symbol]>' is not assignable to type 'Field<T[keyof T]>'.
    Type 'T[string] | T[number] | T[symbol]' is not assignable to type 'T[keyof T]'.
      Type 'T[symbol]' is not assignable to type 'T[keyof T]'.
        Type 'DataType<Type, any>' is not assignable to type 'T[keyof T]'.
          Type 'symbol' is not assignable to type 'keyof T'.
            Type 'symbol' is not assignable to type 'string | number'.
```

The solution is to update ts-node and run it in transpile-only mode.

Closes https://issues.apache.org/jira/browse/ARROW-4395

Author: ptaylor <paul.e.taylor@me.com>
Author: Paul Taylor <paul.e.taylor@me.com>

Closes #3504 from trxcllnt/js/fix-tsnode-typecheck and squashes the following commits:

066327f0 <Paul Taylor> Merge branch 'master' into js/fix-tsnode-typecheck
89b2a7cc <ptaylor> fix ts-node error running bin/arrow2csv